In [1]:
#importing pandas for data operations and numpy for mathematical operations.
import pandas as pd
import numpy as np

In [2]:
pip install seaborn


[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [3]:
#importing seaborn as sb.#installing seaborn for better visulisation in later stages of project.
import seaborn as sb

In [4]:
#using pd, we are reading dataset from csv file and storing the dataset in pdata variable.
pdata=pd.read_csv('allpgrmplacement.csv')

In [5]:
#info() to specfically get datatypes of features in dataset (used for cleaning preprocess)
pdata.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   sl_no           215 non-null    int64  
 1   gender          215 non-null    object 
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    object 
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    object 
 6   hsc_s           215 non-null    object 
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    object 
 9   workex          215 non-null    object 
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    object 
 12  mba_p           215 non-null    float64
 13  status          215 non-null    object 
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB


In [6]:
#to get initial instances with better dataframe.
pdata.head()

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   
3      4      M  56.00  Central  52.00  Central   Science     52.00   
4      5      M  85.80  Central  73.60  Central  Commerce     73.30   

    degree_t workex  etest_p specialisation  mba_p      status    salary  
0   Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1   Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2  Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3   Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN  
4  Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0

In [7]:
#to know no. of rows and columns in dataset.
pdata.shape

(215, 15)

In [8]:
#converting status placed:1 and notplaced:0 in column.

def convertPlacedOrNot(value):
    if value=='Placed' :
        return 1;
    elif value=='Not Placed' :
        return 0;
    
pdata['status']=pdata['status'].apply(convertPlacedOrNot)

In [9]:
#as the data is already clean we will now convert categorical features into numerical features using onehotencoder.
from sklearn.preprocessing import OneHotEncoder

In [10]:
ohe=OneHotEncoder()

In [11]:
xd=pdata.drop(columns=['sl_no','salary'])

In [12]:
xd

gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p   degree_t  \
0        M  67.00   Others  91.00   Others  Commerce     58.00   Sci&Tech   
1        M  79.33  Central  78.33   Others   Science     77.48   Sci&Tech   
2        M  65.00  Central  68.00  Central      Arts     64.00  Comm&Mgmt   
3        M  56.00  Central  52.00  Central   Science     52.00   Sci&Tech   
4        M  85.80  Central  73.60  Central  Commerce     73.30  Comm&Mgmt   
..     ...    ...      ...    ...      ...       ...       ...        ...   
210      M  80.60   Others  82.00   Others  Commerce     77.60  Comm&Mgmt   
211      M  58.00   Others  60.00   Others   Science     72.00   Sci&Tech   
212      M  67.00   Others  67.00   Others  Commerce     73.00  Comm&Mgmt   
213      F  74.00   Others  66.00   Others  Commerce     58.00  Comm&Mgmt   
214      M  62.00  Central  58.00   Others   Science     53.00  Comm&Mgmt   

    workex  etest_p specialisation  mba_p  status  
0       No     55.0         Mkt&HR  58.80       1  
1      Yes     86.5        Mkt&Fin  66.28       1  
2       No     75.0        Mkt&Fin  57.80       1  
3       No     66.0         Mkt&HR  59.43       0  
4       No     96.8        Mkt&Fin  55.50       1  
..     ...      ...            ...    ...     ...  
210     No     91.0        Mkt&Fin  74.49       1  
211     No     74.0        Mkt&Fin  53.62       1  
212    Yes     59.0        Mkt&Fin  69.72       1  
213     No     70.0         Mkt&HR  60.23       1  
214     No     89.0         Mkt&HR  60.22       0  

[215 rows x 13 columns]

In [13]:
#fiting the feature need to be converted.
ohe.fit(xd[['gender','ssc_b','hsc_b','hsc_s','degree_t','workex','specialisation']])

OneHotEncoder()

In [14]:
#seeing what unique values does the feautures consist of with datatypes.
ohe.categories_

[array(['F', 'M'], dtype=object),
 array(['Central', 'Others'], dtype=object),
 array(['Central', 'Others'], dtype=object),
 array(['Arts', 'Commerce', 'Science'], dtype=object),
 array(['Comm&Mgmt', 'Others', 'Sci&Tech'], dtype=object),
 array(['No', 'Yes'], dtype=object),
 array(['Mkt&Fin', 'Mkt&HR'], dtype=object)]

In [15]:
#to convert the colums of x we import make column transformer.
from sklearn.compose import make_column_transformer

In [16]:
#we assign what method is used (ohe) and the columns to be converted to make_column_transformer.
#(case: remainder='passthrough' if a column not mentioned in column categories[] which is already in numeric value to passthrough as it is.)
column_transfer=make_column_transformer((OneHotEncoder(categories=ohe.categories_),['gender','ssc_b','hsc_b','hsc_s','degree_t','workex','specialisation']),remainder='passthrough')

In [17]:
column_transfer

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(categories=[array(['F', 'M'], dtype=object),
                                                           array(['Central', 'Others'], dtype=object),
                                                           array(['Central', 'Others'], dtype=object),
                                                           array(['Arts', 'Commerce', 'Science'], dtype=object),
                                                           array(['Comm&Mgmt', 'Others', 'Sci&Tech'], dtype=object),
                                                           array(['No', 'Yes'], dtype=object),
                                                           array(['Mkt&Fin', 'Mkt&HR'], dtype=object)]),
                                 ['gender', 'ssc_b', 'hsc_b', 'hsc_s',
                                  'degree_t', 'workex', 'specialisation'])])

In [18]:
#fitting the transformed columns to x dataset with fit_transform method.
transformeddata=column_transfer.fit_transform(xd)

In [19]:
transformeddata

array([[ 0.  ,  1.  ,  0.  , ..., 55.  , 58.8 ,  1.  ],
       [ 0.  ,  1.  ,  1.  , ..., 86.5 , 66.28,  1.  ],
       [ 0.  ,  1.  ,  1.  , ..., 75.  , 57.8 ,  1.  ],
       ...,
       [ 0.  ,  1.  ,  0.  , ..., 59.  , 69.72,  1.  ],
       [ 1.  ,  0.  ,  0.  , ..., 70.  , 60.23,  1.  ],
       [ 0.  ,  1.  ,  1.  , ..., 89.  , 60.22,  0.  ]])

In [20]:
#making a proper dataframe and using get_features_name_out from x.columns to automatically assign column name to dataframe.
transformed_df = pd.DataFrame(transformeddata, columns=column_transfer.get_feature_names_out(xd.columns))

In [21]:
transformed_df

onehotencoder__gender_F  onehotencoder__gender_M  \
0                        0.0                      1.0   
1                        0.0                      1.0   
2                        0.0                      1.0   
3                        0.0                      1.0   
4                        0.0                      1.0   
..                       ...                      ...   
210                      0.0                      1.0   
211                      0.0                      1.0   
212                      0.0                      1.0   
213                      1.0                      0.0   
214                      0.0                      1.0   

     onehotencoder__ssc_b_Central  onehotencoder__ssc_b_Others  \
0                             0.0                          1.0   
1                             1.0                          0.0   
2                             1.0                          0.0   
3                             1.0                          0.0   
4                             1.0                          0.0   
..                            ...                          ...   
210                           0.0                          1.0   
211                           0.0                          1.0   
212                           0.0                          1.0   
213                           0.0                          1.0   
214                           1.0                          0.0   

     onehotencoder__hsc_b_Central  onehotencoder__hsc_b_Others  \
0                             0.0                          1.0   
1                             0.0                          1.0   
2                             1.0                          0.0   
3                             1.0                          0.0   
4                             1.0                          0.0   
..                            ...                          ...   
210                           0.0                          1.0   
211                           0.0                          1.0   
212                           0.0                          1.0   
213                           0.0                          1.0   
214                           0.0                          1.0   

     onehotencoder__hsc_s_Arts  onehotencoder__hsc_s_Commerce  \
0                          0.0                            1.0   
1                          0.0                            0.0   
2                          1.0                            0.0   
3                          0.0                            0.0   
4                          0.0                            1.0   
..                         ...                            ...   
210                        0.0                            1.0   
211                        0.0                            0.0   
212                        0.0                            1.0   
213                        0.0                            1.0   
214                        0.0                            0.0   

     onehotencoder__hsc_s_Science  onehotencoder__degree_t_Comm&Mgmt  ...  \
0                             0.0                                0.0  ...   
1                             1.0                                0.0  ...   
2                             0.0                                1.0  ...   
3                             1.0                                0.0  ...   
4                             0.0                                1.0  ...   
..                            ...                                ...  ...   
210                           0.0                                1.0  ...   
211                           1.0                                0.0  ...   
212                           0.0                                1.0  ...   
213                           0.0                                1.0  ...   
214                           1.0                                1.0  ...   

     onehotencoder__workex_N

In [22]:
#renaming columns for better readability.
transformed_df.rename(columns={'onehotencoder__gender_F':'F','onehotencoder__gender_M':'M','onehotencoder__ssc_b_Central':'boardofsscCentral','onehotencoder__ssc_b_Others':'boardofsscOther','onehotencoder__hsc_b_Central':'boardofhscCentral','onehotencoder__hsc_b_Others':'boardofhscOther','onehotencoder__hsc_s_Arts':'specArts','onehotencoder__hsc_s_Commerce':'specCommerce','onehotencoder__hsc_s_Science':'specScience','onehotencoder__degree_t_Comm&Mgmt':'degcomm&mgmt','onehotencoder__degree_t_Others ':'degreeOthers','onehotencoder__degree_t_Sci&Tech':'degreesci&tech','onehotencoder__workex_No':'expN','onehotencoder__workex_Yes':'expY','onehotencoder__specialisation_Mkt&Fin':'MspecMkt&Fin','onehotencoder__specialisation_Mkt&HR':'MspecMkt&HR','remainder__ssc_p':'sscp','remainder__hsc_p':'hscp','remainder__degree_p':'degp','remainder__etest_p':'etestp','remainder__mba_p':'mbap','remainder__status':'status'},inplace=True)

In [23]:
transformed_df

F    M  boardofsscCentral  boardofsscOther  boardofhscCentral  \
0    0.0  1.0                0.0              1.0                0.0   
1    0.0  1.0                1.0              0.0                0.0   
2    0.0  1.0                1.0              0.0                1.0   
3    0.0  1.0                1.0              0.0                1.0   
4    0.0  1.0                1.0              0.0                1.0   
..   ...  ...                ...              ...                ...   
210  0.0  1.0                0.0              1.0                0.0   
211  0.0  1.0                0.0              1.0                0.0   
212  0.0  1.0                0.0              1.0                0.0   
213  1.0  0.0                0.0              1.0                0.0   
214  0.0  1.0                1.0              0.0                0.0   

     boardofhscOther  specArts  specCommerce  specScience  degcomm&mgmt  ...  \
0                1.0       0.0           1.0          0.0           0.0  ...   
1                1.0       0.0           0.0          1.0           0.0  ...   
2                0.0       1.0           0.0          0.0           1.0  ...   
3                0.0       0.0           0.0          1.0           0.0  ...   
4                0.0       0.0           1.0          0.0           1.0  ...   
..               ...       ...           ...          ...           ...  ...   
210              1.0       0.0           1.0          0.0           1.0  ...   
211              1.0       0.0           0.0          1.0           0.0  ...   
212              1.0       0.0           1.0          0.0           1.0  ...   
213              1.0       0.0           1.0          0.0           1.0  ...   
214              1.0       0.0           0.0          1.0           1.0  ...   

     expN  expY  MspecMkt&Fin  MspecMkt&HR   sscp   hscp   degp  etestp  \
0     1.0   0.0           0.0          1.0  67.00  91.00  58.00    55.0   
1     0.0   1.0           1.0          0.0  79.33  78.33  77.48    86.5   
2     1.0   0.0           1.0          0.0  65.00  68.00  64.00    75.0   
3     1.0   0.0           0.0          1.0  56.00  52.00  52.00    66.0   
4     1.0   0.0           1.0          0.0  85.80  73.60  73.30    96.8   
..    ...   ...           ...          ...    ...    ...    ...     ...   
210   1.0   0.0           1.0          0.0  80.60  82.00  77.60    91.0   
211   1.0   0.0           1.0          0.0  58.00  60.00  72.00    74.0   
212   0.0   1.0           1.0          0.0  67.00  67.00  73.00    59.0   
213   1.0   0.0           0.0          1.0  74.00  66.00  58.00    70.0   
214   1.0   0.0           0.0          1.0  62.00  58.00  53.00    89.0   

      mbap  status  
0    58.80     1.0  
1    66.28     1.0  
2    57.80     1.0  
3    59.43     0.0  
4    55.50     1.0  
..     ...     ...  
210  74.49     1.0  
211  53.62     1.0  
212  69.72     1.0  
213  60.23     1.0  
214  60.22     0.0  

[215 rows x 22 columns]

In [24]:
transformed_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   F                               215 non-null    float64
 1   M                               215 non-null    float64
 2   boardofsscCentral               215 non-null    float64
 3   boardofsscOther                 215 non-null    float64
 4   boardofhscCentral               215 non-null    float64
 5   boardofhscOther                 215 non-null    float64
 6   specArts                        215 non-null    float64
 7   specCommerce                    215 non-null    float64
 8   specScience                     215 non-null    float64
 9   degcomm&mgmt                    215 non-null    float64
 10  onehotencoder__degree_t_Others  215 non-null    float64
 11  degreesci&tech                  215 non-null    float64
 12  expN                            215 

In [25]:
## as the datatype of all the features are float now cleaning has been done. Lets proceed with processing.
cleaned_data=transformed_df
#assigning x and y.
x=cleaned_data.drop(columns=['status'])
y=cleaned_data['status']

In [26]:
#importing train test split
from sklearn.model_selection import train_test_split

In [27]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=10)

In [28]:
#importing classification regression models
from sklearn.linear_model import LogisticRegression
Lor=LogisticRegression(solver='lbfgs', max_iter=1000)#to increase max_iteration (warning)
from sklearn.tree import DecisionTreeClassifier
Dt=DecisionTreeClassifier()
from sklearn.ensemble import RandomForestClassifier
Rf=RandomForestClassifier()



In [29]:
#fitting classification model on dataset.
Lor.fit(xtrain,ytrain)

LogisticRegression(max_iter=1000)

In [30]:
Dt.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [31]:
Rf.fit(xtrain,ytrain)

RandomForestClassifier()

In [32]:
#library to check the classification is how much accurate.
from sklearn.metrics import confusion_matrix

In [33]:
ypred_lor=Lor.predict(xtest)
ypred_dt=Dt.predict(xtest)
ypred_rf=Rf.predict(xtest)


In [34]:
ypred_lor

array([1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
ypred_dt

array([1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
ypred_rf

array([1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0.,
       1., 1., 1., 0., 1., 1., 1., 1., 1.])

In [37]:
confusion_matrix(ytest,ypred_lor)

array([[ 9,  9],
       [ 1, 24]])

In [38]:
confusion_matrix(ytest,ypred_dt)

array([[ 8, 10],
       [ 4, 21]])

In [39]:
confusion_matrix(ytest,ypred_rf)

array([[10,  8],
       [ 1, 24]])

In [40]:
#classification has been done,now we can choose any classification model among them but for better accuracy I will choose random_forest
#making the model file for prediction
import pickle
pickle.dump(Rf, open('placementmodel.pkl','wb'))

In [41]:
#checking the model
model=pickle.load(open('placementmodel.pkl','rb'))
ypred_rf2=model.predict(xtest)

In [42]:
confusion_matrix(ytest,ypred_rf2)

array([[10,  8],
       [ 1, 24]])

In [43]:
##The training is done. Now proceeding for website.